### ISSUE TITLE
Music Queue

### ISSUE THREAD

**Issue by ChickenNugget0430** [BlackyChan1800/VillainsBot#6]
Implement a queue system where you can view all songs that are to be played

[.queue, .q](https://discord.com/channels/788021898146742292/795820101433032774/856490753216086049)

send embed list of songs with buttons or pages every 10 songs

**Comment by miketrethewey** [comment]
Fixed by 56415217302938dcfdab9a749a656626ab7d6aa0 and 662d4525056d2ed751024116f3b30eb858293721
